"""
Application constants
"""

# File types
SUPPORTED_FILE_TYPES = ['.txt']
MAX_FILE_SIZE = 100 * 1024 * 1024  # 100 MB

# Chunking
DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 100
MIN_CHUNK_SIZE = 100
MAX_CHUNK_SIZE = 2000

# Embedding
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384

# Pinecone
PINECONE_METRIC = "cosine"
PINECONE_CLOUD = "aws"
PINECONE_DEFAULT_NAMESPACE = "default"

# Mistral
MISTRAL_TIMEOUT = 60
MISTRAL_MAX_TOKENS = 500
MISTRAL_TEMPERATURE = 0.7

# RAG
DEFAULT_TOP_K = 5
SIMILARITY_THRESHOLD = 0.7
MAX_CONTEXT_LENGTH = 2000

# Rate Limiting
DEFAULT_RATE_LIMIT_MINUTE = 10
DEFAULT_RATE_LIMIT_HOUR = 100

# Circuit Breaker
DEFAULT_FAILURE_THRESHOLD = 3
DEFAULT_RECOVERY_TIMEOUT = 60
DEFAULT_HALF_OPEN_TIMEOUT = 30
DEFAULT_MIN_CALLS_TO_TRIP = 10

# Sync
DEFAULT_SYNC_INTERVAL = 5  # minutes
MAX_RETRY_ATTEMPTS = 3
RETRY_BACKOFF_FACTOR = 2

# Security
MAX_QUERY_LENGTH = 500
MAX_PROMPT_LENGTH = 2000

# Logging
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# HTTP Status Codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_429_TOO_MANY_REQUESTS = 429
HTTP_500_INTERNAL_SERVER_ERROR = 500

# Error Codes
ERROR_INVALID_QUERY = "INVALID_QUERY"
ERROR_RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
ERROR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
ERROR_PINECONE_FAILURE = "PINECONE_FAILURE"
ERROR_MEGA_FAILURE = "MEGA_FAILURE"
ERROR_MISTRAL_FAILURE = "MISTRAL_FAILURE"
ERROR_INTERNAL = "INTERNAL_ERROR"

# Messages
MSG_RATE_LIMIT_EXCEEDED = "Rate limit exceeded. Please try again later."
MSG_INVALID_QUERY = "Invalid query provided."
MSG_SERVICE_UNAVAILABLE = "Service currently unavailable."
MSG_CONTENT_MODERATION = "Content violates ethical guidelines."
MSG_FALLBACK_USED = "Using fallback response due to RAG failure."

# Environment
ENV_DEV = "development"
ENV_STAGING = "staging"
ENV_PROD = "production"

# Performance
MAX_BATCH_SIZE = 100
MAX_CONCURRENT_DOWNLOADS = 5
DEFAULT_TIMEOUT = 30  # seconds